function OnStart()
    assert(self:HasAnimator())
    local a = self:GetAnimator()
    assert(#a:GetClips() == 3)
    assert(not a:Play("missing"))
    local g = a:GetGraph()
    g:Clear()
    assert(g:AddState("Idle", "Idle"))
    assert(g:AddState("Run", "Run", true, 1.0))
    assert(g:AddTransition("Idle", "Run", "speed", AnimationComparison.Greater, 3.0))
    assert(a:StartGraph("Idle"))
    a:SetFloat("speed", 5)
    a:SetBool("grounded", true)
    assert(a:GetFloat("grounded") == 1)
    assert(a:GetFloat("unknown") == 0)
    a:Pause()
    assert(not a:IsPlaying())
    a:Resume()
    a:Seek(0.0)
    assert(a:GetDuration() > 0 and a:GetCurrentClip() == "Idle")
    assert(self:AddAnimator():GetCurrentClip() == "Idle")
    self:GetAnimatorComponent().previewInEditor = false
    self:GetAnimatorComponent().player:SetFloat("testPassed", 1)
end
